TRI_LAYER_ENABLE = no

MOUSEKEY_ENABLE = yes
# Link Time Optimization (LTO), significantly reduce the compiled size
LTO_ENABLE = yes
COMMAND_ENABLE = no
KEY_LOCK_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
WEBUSB_ENABLE = yes
ORYX_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
CAPS_WORD_ENABLE = yes
